### ISSUE TITLE
PinataParty × WildStacker issue

### ISSUE THREAD

**Issue by ItchyDitchy** [BG-Software-LLC/WildStacker#204]
**Minecraft's Version**
1.16 Spigot

**Plugin's Version**:
WildStacker-b142

**Describe the bug**
Spawning a llama(from pinata party) then hitting it with anything while the entity's stacking feature is enabled, kills the entity immediately. The llama should have taken more than x amount of hits depending on the configuration for pinata party.

**To Reproduce**
Spawn a pinata party llama, hit it with anything with the entity stacking feature enabled.

**Additional information**

[PinataParty](https://www.spigotmc.org/resources/pinataparty-interactive-event-%E2%9C%A8-aio-voting-system-%E2%9C%A8-1-12-x-1-17-x.59318/) **Plugin Hook**
  **Link:** [PinataParty Plugin Link](https://www.spigotmc.org/resources/pinataparty-interactive-event-%E2%9C%A8-aio-voting-system-%E2%9C%A8-1-12-x-1-17-x.59318/)

**Versions**
- WildStacker-b142
- PinataParty-2.29.1

**Issues:**
- With WildStacker and PinataParty plugin together. A llama(PinataParty) seems to die instantly when one-shot(WildStacker) is enabled.

**Configuration Snippets:**
```yaml
# Here you can configurable all features related to stacked entities.
entities:
  # Should entities get stacked on the server?
  enabled: true
...
...
...
  # Instant-kill will kill the entire stack instead of unstack it by one.
  # When an entire stack dies, their drops are getting multiplied.
  # EntityType list: https://bg-software.com/entities/
  # DamageCause list:  https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html
  # You can combine both filters using "ENTITY_TYPE:DAMAGE_CAUSE" or "ENTITY_TYPE:SPAWN_REASON"
  # If you don't want instant-kill, use "instant-kill: []"
  instant-kill:
    - ALL
...
...
...
  # When enabled, entities will be one shot by specific tools.
  one-shot:
    # Should this feature be enabled?
    enabled: false
    # A list of tools that can one shot entities.
    tools:
      - "NETHERITE_SWORD"
    # A list of entities that will be one shot.
    # EntityType list: https://bg-software.com/entities/
    # SpawnReason list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
    # You can combine both filters using "ENTITY_TYPE:SPAWN_REASON"
    whitelist:
      - "HORSE:SPAWNER"
  ```
  
  **Tests:**
- Netherite Sword hits Horse(WildStacker) : Horse stack dies instantly **✓**
- Netherite Sword hits Llama(WildStacker) : Llama gets damaged(doesn't die in one-shot) **✓**
- ANY ITEM hits Llama(PinataParty) : Llama dies **❌**
