### ISSUE TITLE
Config value do not work

### ISSUE THREAD

**Issue by Ammorack** [BG-Software-LLC/WildStacker#375]
### Minecraft's Version

1.16.5  - PurpurSpigot

### Plugin's Version

WildStacker-3.6.1-b234.jar  
Latest build from Jenkins 
[Link to Plugin](https://hub.bg-software.com/job/WildStacker/234/)

### Describe the bug

Config part.
```
  explosions:
    # Should spawners get dropped when exploded by TNT or Creepers?
    enabled: true

    # Should the spawner item go straight into the player's inventory instead of dropping on ground?
    drop-to-inventory: false
```
Drop-to-inventory variable is not working, it will drop spawners in inventory with both states - [TRUE / FALSE]

### To Reproduce

Change value to false  - reload config - go ingame and blow spawner up.
Drop-to-inventory: false

* Spawner in all cases will drop in inventory regardless of value false.

### Additional Information

![image](https://user-images.githubusercontent.com/78719509/142212958-6e2fca04-544d-452b-8fff-693cd1f54f1c.png)
![image](https://user-images.githubusercontent.com/78719509/142213001-f792931d-80a4-4216-a26a-2c12b99f4dbf.png)
![image](https://user-images.githubusercontent.com/78719509/142213121-ea60c3c2-e9f7-4e7c-b746-dcf5a7ec8bf6.png)
![image](https://user-images.githubusercontent.com/78719509/142213134-5a6cd58e-94f9-4918-bbc6-82fd1427192b.png)

========================================
**Images with code are from guy, who answered to me in BG discord (ItchyDitchy#8435)**
============================
