### ISSUE TITLE
Spawner upgrades don't filter per-entity type.

### ISSUE THREAD

**Issue by ItzSave** [BG-Software-LLC/WildStacker#521]
### Minecraft's Version

1.18.2

### Plugin's Version

3.7.0 b309

### Describe the bug

Spawner upgrades don't filter per-entity when ladders are set to the entity. Meaning you can't have per-spawner custom upgrades.

### To Reproduce

```
      'blaze':
        entities:
        - BLAZE
        blaze-default:
          next-upgrade: blaze-rare
          id: 0
          nearby-players: 16
          icon:
            type: BLAZE_ROD
            name: '&6Default'
            lore:
            - '&fThis upgrade is free of charge'
        blaze-rare:
          id: 1
          display: '&7 [Rare]'
          cost: 5000000
          icon:
            type: BLAZE_ROD
            name: '&6&lRare &e&lUpgrade'
            lore:
            - '&8Spawner Upgrade'
      'iron-golem':
        entities:
        - IRON_GOLEM
        iron_golem-default:
          next-upgrade: iron_golem-rare
          id: 0
          nearby-players: 16
          icon:
            type: IRON_INGOT
            name: '&6Default'
            lore:
            - '&fThis upgrade is free of charge'
        iron_golem-rare:
          id: 3
          display: '&7 [Rare]'
          cost: 10000000
          icon:
            type: IRON_INGOT
            name: '&7&lRare &f&lUpgrade'
            lore:
            - '&8Spawner Upgrade'          
```

The above example will show the blaze upgrade inside of the iron golem's upgrade menu making the iron golem upgrade unusable.

### Additional Information

Expected/desired behavior would be for the entities list to act as a sort of whitelist of which upgrades appear in the menus of which entities.
