### ISSUE TITLE
spawner issue on survival mode [video and step to reproduce] 

### ISSUE THREAD

**Issue by HamtaBot** [BG-Software-LLC/WildStacker#731]
### Minecraft's Version

1.19.3

### Plugin's Version

dev 408

### Describe the bug

when placing a stack spawner on creative mode mobs are spawning as intended but when placing a stack of spawners on survival mode its spawning only like if there was 1 spawner here is the video to explain the bug watch until the end 

https://www.youtube.com/watch?v=2mZXom50KwE

here is my config : https://pastebin.com/am7MWx1p

### To Reproduce

do exactly what i did on the video and you will see the issue

**Comment by OmerBenGera** [comment]
Your config makes no sense:
```yaml
  # Blacklisted entities are entities that won't get stacked.
  # EntityType list: https://bg-software.com/entities/
  # SpawnReason list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
  # You can combine both filters using "ENTITY_TYPE:SPAWN_REASON"
  # If you wish to disable blacklisted entities, use "blacklist: []"
  blacklist:
  - WITHER
  - BAT
 
  # Whitelisted entities are entities that will get stacked.
  # EntityType list: https://bg-software.com/entities/
  # SpawnReason list: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/CreatureSpawnEvent.SpawnReason.html
  # You can combine both filters using "ENTITY_TYPE:SPAWN_REASON"
  # If you wish to disable whitelisted entities, use "whitelist: []"
  whitelist:
  - SPAWNER
  ```
  You can't have both whitelist and blacklist. Set the blacklist to empty, check if it still occurs.
