### ISSUE TITLE
Item from Loot tables not glowing for some reason

### ISSUE THREAD

**Issue by Crazz-y** [BG-Software-LLC/WildStacker#804]
### Minecraft's Version

Minecraft version - 1.16.5
Server Version - 1.18.2

### Plugin's Version

2023.1-b428

### Describe the bug

I have custom loot which drops depending if the spawner is upgraded or not. I configured this around a month or two ago, and all was working fine. However just today, i wanted to change the design of the loot, by changing the name and adding a line of lore to the item. When reloading the plugin and killing the upgraded mob i noticed that the mob was dropping the loot, with the new name and lore, however it was no longer glowing. I havent done anything to the glow: .

```
{
        "upgrade": "infusedVillager1",
        "killedByPlayer": true,
        "chance": 100,
        "items": [
          {
            "type": "EMERALD",
            "chance": 100,
            "min": 1,
            "max": 1,
            "looting": true,
            "glow": true,
            "name": "&a&lInfused &2&lEmerald &7[Tier I]",
            "lore": [
              "&8Custom Drop"
            ],
            "nbt-data": {
              "enchblock": 1
            }
          }
        ]
      },
```

### To Reproduce

Add this to config
```
'3':
        entities:
        - VILLAGER
        default:
          next-upgrade: infusedVillager1
          nearby-players: 16
          icon:
            type: STONE
            name: '&fBasic'
            lore:
            - '&8Current Upgrade'
            - '&7 '
            - '&2&lInformation:'
            - '&7 &2| &aPrice: &fFree'
            - '&7 &2| &aDrop: &fEmerald'
            - '&7 '
        infusedVillager1:
          id: 4
          next-upgrade: infusedVillager2
          display: '&7 (&2&k&l;&a&lInfused&2&k&l;&7) [Tier I]'
          cost: 38070000
          icon:
            type: EMERALD
            enchants:
              DAMAGE_ALL: 1
            flags:
            - HIDE_ENCHANTS
            name: '&2&k&l;&a&lInfused&2&k&l; &2Villager &7[Tier I]'
            lore:
            - '&8Spawner Upgrade'
            - '&7 '
            - '&2&lInformation:'
            - '&7 &2| &aPrice: &f$%cost%'
            - '&7 &2| &aDrop: &fInfused Emerald &7[Tier I]'
            - '&7 '
            - '&7(( Click to upgrade to &2Infused Villager&7 [Tier I] ))'
```

Then in villager loot table add this after the normal drop
```
{
        "upgrade": "infusedVillager1",
        "killedByPlayer": true,
        "chance": 100,
        "items": [
          {
            "type": "EMERALD",
            "chance": 100,
            "min": 1,
            "max": 1,
            "looting": true,
            "glow": true,
            "name": "&a&lInfused &2&lEmerald &7[Tier I]",
            "lore": [
              "&8Custom Drop"
            ],
            "nbt-data": {
              "enchblock": 1
            }
          }
        ]
      },
```

Next kill a villager that has been spawned from the upgraded spawner. You can give yourself a spawner using `/stacker give <PlayerName> spawner villager 1 infusedVillager1`
