### ISSUE TITLE
Mob spawning as an adult

### ISSUE THREAD

**Issue by WarnDa** [BG-Software-LLC/WildStacker#967]
### Minecraft's Version

Paper 1.20.4-1.21 (tested on both)

### Plugin's Version

b86
**The issue do not occur on b71 and start to happen on b72**
Commit that created this issue : https://github.com/BG-Software-LLC/WildStacker/commit/c8c7a986024c882e33c2b23d2c2214cf47799e10

### Describe the bug

If you use 
`  smart-breeding:
    enabled: true
    # When enabled, items for breeding will be consumed from the entire inventory instead of only hand.
    consume-entire-inventory: true
`
and reproduce a mob, it will spawn an adult and not a baby

### To Reproduce

- use config option : 
```
smart-breeding:
    enabled: true
    # When enabled, items for breeding will be consumed from the entire inventory instead of only hand.
    consume-entire-inventory: true
```
- reproduce 2 stacked cow
- it will spawn a baby

### **The issue do not occur on b71 and start to happen on b72**
Commit that created this issue : https://github.com/BG-Software-LLC/WildStacker/commit/c8c7a986024c882e33c2b23d2c2214cf47799e10
